export const TOAST_BUTTON = '.toast__button';
export const REGISTER_RBUTTON = 'div.overall div.site-navbar:nth-child(3) div.ui.middle.aligned.grid.header-container.py-5.px-4:nth-child(1) div.four.wide.computer.sixteen.wide.mobile.sixteen.wide.tablet.column.login-container.px-4.flex-end.only-desktop > a.btn.btn-register.btn-first.btn-border.btn-bg.font-semibold.fsize-14:nth-child(2)';
export const EMAIL_FIELD = 'div.overall div.ui.container.mt-5.body-content:nth-child(4) div.ui.grid div.ten.wide.computer.sixteen.wide.mobile.sixteen.wide.tablet.column div.ui.segment.register div.ui.container form.ui.form:nth-child(2) div.mb-input:nth-child(1) div.mb-input div.field.mb-input.full-width-input div.ui.input:nth-child(2) > input:nth-child(1)';
export const DOCUMENT_FIELD = '//input[@name="documentNumber"]';
export const NAME_FIELD = 'div.overall div.ui.container.mt-5.body-content:nth-child(4) div.ui.grid div.ten.wide.computer.sixteen.wide.mobile.sixteen.wide.tablet.column div.ui.segment.register div.ui.container form.ui.form:nth-child(2) div.mb-input:nth-child(4) div.field.mb-input div.ui.input:nth-child(2) > input:nth-child(1)';
export const LASTNAME_FIELD = '//input[@name="lastName"]';
export const CELLPHONE_FIELD = '//input[@name="cellPhone"]';
export const PHONE_FIELD = '//input[@name="phone"]';
export const EXT_FIELD = '//input[@name="ext"]';
export const POSITION_FIELD = '//input[@name="position"]';
export const DOC_FIELD = '//body/div[@id="root"]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/form[1]/div[2]/div[1]/div[1]';
export const SELECTDOC_FIELD = '(//*[contains(text(),"Cédula Ciudadanía")])';
